config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'products#index'
  get    '/about',    to: 'pages#about'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  resources :categories
  resources :products
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  validates :name,  presence: true, length: { minimum: 5, maximum: 20 }
  validates :price, presence: true
  validate  :picture_size
  belongs_to :category

  private
  # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true,
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                              format: { with: VALID_EMAIL_REGEX },
                              uniqueness: { case_sensitive: false }
  has_secure_password

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      #store_location
      flash[:danger] = "Sorry! Bitte anmelden."
      redirect_to login_url
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :new, :create, :destroy]
  before_action :set_categories, only: [:new, :create, :index, :show, :edit, :update]

  def show
    @category = Category.find(params[:id])
    @product = Product.all
  end

  def index
    logged_in_user
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
     flash[:success] = "Erfolgreich! Die Kategorie wurde editiert."
     redirect_to category_path(@category)
    else
     flash[:danger] = "Sorry! Die Kategorie wurde nicht editiert."
     render 'edit'
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    flash[:success] = "Category deleted"
    redirect_to categories_url
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def set_categories
    @allCategories = Category.all
  end

  def logged_in_user
    unless logged_in?
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def about
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :show, :destroy]
  before_action :set_categories, only: [:new, :create, :index, :show, :edit, :update]
  before_action :logged_in_user, only: [:create, :edit, :update, :destroy]

  def new
    @product = Product.new
    @categories = Category.all.map{ |cat| [cat.name, cat.id] }
  end

  def create
    @product = Product.new(product_params)
    if @product.save
     flash[:success] = "Erfolgreich! Produkt erfolgreich angelegt."
     redirect_to product_path(@product)
    else
     render 'new'
    end
  end

  def index
    @product = Product.all
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)
     flash[:success] = "Erfolgreich! Das Produkt wurde editiert."
     redirect_to product_path(@product)
    else
     flash[:danger] = "Sorry! Das Produkt wurde nicht editiert."
     render 'edit'
    end
  end

  def destroy
   @product.destroy
   flash[:notice] = "Erfolgreich! Das Produkt wurde entfernt."
   redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :price, :category_id, :picture)
    end

    def set_categories
      @allCategories = Category.all
    end

    def set_product
      @product = Product.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_categories, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    #logger.debug "Found User ID : #{user.id}"
    if user && user.authenticate(params[:session][:password])
      #log_in user
      #logger.debug "logged in User with email #{user.email}"
      session[:user_id] = user.id
      #logger.debug "Session User id: #{session[:user_id]}"
      redirect_to products_path      #login etc.
   else
     flash.now[:danger] = 'Sorry! Falsche Email/Password Kombination.'
     render 'new'
   end
 end

  def destroy
    log_out
    redirect_to root_url
  end

  private
    def set_categories
      @allCategories = Category.all
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :show, :new, :create, :destroy]
  before_action :set_categories, only: [:new, :create, :index, :show, :edit, :update]
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  private

  def user_params
    params.require(:user).permit(:username, :email, :password,
                                 :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      #store_location
      flash[:danger] = "Sorry! Bitte anmelden."
      redirect_to login_url
    end
  end

  def set_categories
    @allCategories = Category.all
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def last_change
    t = Product.maximum(:updated_at)
    t ||= Time.new
    t.strftime("%d.%m.%Y %H:%M")
  end

  def get_hostname
    hostname = request.host
  end

  def build_share_link(path)
    link = "https://" + get_hostname + path
  end

  def build_whatsapp_link(text, path)
    require 'uri'
    msg = URI::encode(text)
    link = "whatsapp://send?text=" + msg + "%3A%20" + build_share_link(path)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      logger.debug "current_user UserID: #{session[:user_id]}"
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/categories/edit.html.erb
<% provide(:title, "Edit Category") %>
<div class="category">
  <h2>Kategorie ändern</h2>
</div>

<div class="form-style">
    <%= form_for(@category) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Änderung speichern", class: "btn-primary" %>
    <% end %>

</div>

app/views/categories/index.html.erb
<div class="category">
<h2>Alle Produkte</h2>
</div>
<div class="grid">
  <% @allCategories.each do |cat| %>
  <div class="product">
    <div class="product-name">
      <%= link_to cat.name, category_path(cat.id) %>
    </div>
    <div class="product-actions">
     <%= link_to "Edit", edit_category_path(cat), class: "btn-warning" %>
     <%= link_to "Delete", category_path(cat), method: :delete, data: { confirm: "Are you sure you want to delete this product?"}, class: "btn-error" %>
    </div>
  </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<% provide(:title, "New Category") %>
<div class="category">
  <h2>Neue Kategorie anlegen</h2>
</div>

<div class="form-style">
    <%= form_for(@category) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Kategorie anlegen", class: "btn-primary" %>
    <% end %>

</div>

app/views/categories/show.html.erb
<div class="category">
<h2><%= @category.name %> Produkte</h2>
</div>
<div class="grid">
<% @product.where(category_id: @category.id).each do |product| %>
  <div class="product">
    <a href="<%= product_path(product) %>"><%= image_tag product.picture.url if product.picture? %></a>
    <div class="product-name"><%= product.name %></div>
    <div class="product-price"><%= product.price %>€</div>
    <div class="product-messaging">
      <a href="<%= build_whatsapp_link("Ich möchte folgendes Produkt erwerben", product_path(product)) %>" class="btn-primary">WhatsApp</a>
    </div>
  </div>
<% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footerlinks">
    <a href="https://angebote.partylite.de">Shop</a>
    <a href="https://www.facebook.com/groups/partylitebymelb/">Facebook</a>
    <a href="https://www.verkaufspartys.net/melanie.bialowons">Verkaufsparties</a>
  </div>
  <div class="copyright">
    Melanie Bialowons - selbstständige Handelsvertreterin
  </div>
  <div class="change">
    Stand <%= last_change %>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav>
  <%= link_to "Home", root_path %>

  <% @allCategories.each do |cat| %>
    <%= link_to cat.name, category_path(cat.id) %>
  <% end %>
  <% if logged_in? %>
    <%= link_to "Profil", user_path(current_user) %>
    <%= link_to "Kategorien", categories_path %>
    <%= link_to "Log out", logout_path, method: :delete %>
  <% else %>
    <%= link_to "Log in", login_path %>
  <% end %>
</nav>
<% if logged_in? %>
  <div class="adm-new">
    <%= link_to "Neues Produkt", new_product_path, class: "btn-success" %>
    <%= link_to "Neuer Benutzer", new_user_path, class: "btn-success" %>
    <%= link_to "Neue Kategorie", new_category_path, class: "btn-success" %>
  </div>
<% end %>
<header>
  <h1>Ausverkauf</h1>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ausverkauf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="widthh=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Poppins:400,600' %>
    <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Work+Sans' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Ausverkauf</h1>
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>

app/views/pages/index.html.erb
<h1>Willkommen zu meinem Ausverkauf</h1>
Die Produkte sind in zwei Kategorien aufgeteilt:
<%= link_to "Wachs", category_path(1) %>
<%= link_to "Accessoires", category_path(2) %>

app/views/products/_form.html.erb
<div class="form-style">
  <%= form_for(@product) do |f|%>
    <%= f.label :picture %>
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    <% if f.object.picture? %>
      <%= image_tag f.object.picture.url %>
    <% end %>

    <%= f.label :category %>
    <%= f.select(:category_id, options_for_select(@categories || Category.all.map { |c| [ c.name, c.id ] }), :prompt => "Wähle eine!") %>

    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Name des Produkts" %>

    <%= f.label :price %>
    <%= f.text_field :price, placeholder: "Runder Preis" %>

    <%= f.label :description %>
    <%= f.text_area :description, rows: 10, placeholder: "Beschreibungstext" %>

    <%= f.submit "Abspeichern" %>
  <% end %>
</div>

app/views/products/edit.html.erb
<div class="container">
  <h2>Produkt editieren</h2>
  <%= render 'shared/errors', obj: @product %>
  <%= render 'form' %>
</div>

app/views/products/index.html.erb
<div class="category">
<h2>Alle Produkte</h2>
</div>
<div class="grid">
<% @product.each do |product| %>
  <div class="product">
    <a href="<%= product_path(product) %>"><%= image_tag product.picture.url if product.picture? %></a>
    <div class="product-name"><%= product.name %></div>
    <div class="product-price"><%= product.price %>€</div>
    <div class="product-messaging">
      <a href="<%= build_whatsapp_link("Ich möchte folgendes Produkt erwerben", product_path(product)) %>" class="btn-primary">WhatsApp</a>
    </div>
  </div>
<% end %>
</div>

app/views/products/new.html.erb
<div class="container">
  <h2>Ein Produkt anlegen</h2>
  <%= render 'shared/errors', obj: @product %>
  <%= render 'form' %>
</div>

app/views/products/show.html.erb
<div class="container">
<div class="product-view">
  <div><%= image_tag @product.picture.url if @product.picture? %></div>
  <div class="product-name">
    <%= @product.name %>
  </div>
  <div class="product-price">
    <%= @product.price %>€
  </div>
  <% if !logged_in? %>
  <div class="product-messaging">
    <a href="<%= build_whatsapp_link("Ich möchte folgendes Produkt erwerben", product_path(@product)) %>" class="btn-primary">WhatsApp</a>
    <a href="<%= build_share_link(product_path(@product)) %>" class="btn-secondary">Link kopieren</a>
  </div>
  <% else %>
  <div class="product-actions">
   <%= link_to "Edit", edit_product_path(@product), class: "btn-warning" %>
   <%= link_to "Delete", product_path(@product), method: :delete, data: { confirm: "Are you sure you want to delete this product?"}, class: "btn-error" %>
  </div>
  <% end %>
</div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-notice">
  <strong>
  <%= pluralize(obj.errors.count, "error") %>
    prohibited this product from being saved:
  </strong>
  <ul>
  <% @product.errors.full_messages.each do |msg|%>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
 <div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>'>
   <a href="#" class="close" data-dismiss="alert">&#215;</a>
   <%= content_tag :div, msg, :id => "flash_#{name}" is msg.is_a?(String) %>
  </div>
  <% end %>
 </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="category">
  <h2>Profil ändern</h2>
</div>

<div class="form-style">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Änderungen speichern", class: "btn-primary" %>
    <% end %>

</div>

app/views/users/index.html.erb
<div class ="container">
<div class="category">
  <h2>Alle Benutzer</h2>
</div>
<% @users.each do |user| %>
<div class="product-view">
    <%= link_to user.username, user %>
    <%= user.email %>
</div>
<% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, "New user") %>
<div class="category">
  <h2>Neuen Benutzer anlegen</h2>
</div>

<div class="form-style">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Benutzer anlegen", class: "btn-primary" %>
    <% end %>

</div>

app/views/users/show.html.erb
<div class="container">
<div class="category">
  <h2>Benutzerprofil</h2>
</div>
<div class="product-view">
  <div class="product-name">
    <%= @user.username %>
  </div>
  <div class="product-price">
    <%= @user.email %>
  </div>
  <div class="product-actions">
   <%= link_to "Edit", edit_user_path(@user), class: "btn-warning" %>
   <%= link_to "Delete", user_path(@user), method: :delete, data: { confirm: "Are you sure you want to delete this user?"}, class: "btn-error" %>
  </div>
</div>
</div>